In [ ]:
#Sreejoni Roy 

#Reading the parquet file for features and transcations


import pandas as pd

df_items = pd.read_parquet("Tao Yin_Item_features.parquet")
df_users = pd.read_parquet("TaoYin_User_Transactions_v2.parquet")

print("ITEM FEATURES COLUMNS:\n")
print(df_items.dtypes)
print("\nSample rows from item features:\n")
print(df_items.head())

print("\n\nUSER TRANSACTIONS COLUMNS:\n")
print(df_users.dtypes)
print("\nSample rows from user transactions:\n")
print(df_users.head())

ITEM FEATURES COLUMNS:

Articlenr                  int64
EF000001                 float64
EF000002                 float64
EF000003                 float64
EF000004                 float64
                          ...
EFUK0017                 float64
EFUK0019                 float64
ETIM                     float64
statistiek_hoofdgroep     object
statistiek_subgroep       object
Length: 4028, dtype: object

Sample rows from item features:

   Articlenr  EF000001  EF000002  EF000003  EF000004  EF000005  EF000006  \
0   34581962       6.0       NaN       NaN       NaN       NaN       NaN
1   35764300       NaN       NaN       NaN       NaN       NaN       NaN
2   35823358       NaN       NaN       NaN       NaN       NaN       NaN
3   28405226       NaN       NaN       NaN       NaN       NaN       NaN
4   35622440       NaN       NaN       NaN       NaN       NaN       NaN

   EF000007  EF000008  EF000010  ...  EFDE0031  EFDE0032  EFFR0001  EFFR0002  \
0       NaN       6.2       NaN  ...       NaN       NaN       NaN       NaN
1       NaN       NaN       NaN  ...       NaN       NaN       NaN       NaN
2       NaN       NaN       NaN  ...       NaN       NaN       NaN       NaN
3       NaN       NaN       NaN  ...       NaN       NaN       NaN       NaN
4       NaN       NaN       NaN  ...       NaN       NaN       NaN       NaN

   EFNL0014  EFUK0017  EFUK0019   ETIM  statistiek_hoofdgroep  \
0       NaN       NaN       NaN   26.0                      A
1       NaN       NaN       NaN   30.0                      A
2       NaN       NaN       NaN   31.0                      A
3       NaN       NaN       NaN  321.0                      B
4       NaN       NaN       NaN   14.0                      C

   statistiek_subgroep
0                   x1
1                   x2
2                   x3
3                   y1
4                   y2

[5 rows x 4028 columns]


USER TRANSACTIONS COLUMNS:

customer                      int64
invoice                       int64
invoice_date         datetime64[ns]
articlenr                     int64
volume                        int64
sum1                        float64
sum2                        float64
postcode_delivery             int64
postcode_customer             int64
channel                      object
dtype: object

Sample rows from user transactions:

   customer  invoice invoice_date  articlenr  volume     sum1     sum2  \
0      2284  1187467   2020-01-02   32879960      24   343.73   362.30
1      2284  1187467   2020-01-02   32879962      60  1067.64  1119.96
2      2284  1187467   2020-01-02   32841810     120  2214.00  2408.40
3      1704  1191447   2020-01-17   36866802       1    21.52    19.32
4        45  1187691   2020-01-03   34360272       4    28.91    28.49

   postcode_delivery  postcode_customer    channel
0              80413              80413  Tel 86041
1              80413              80413  Tel 86041
2              80413              80413  Tel 86041
3              81724              81724  OTC 81812
4              81796              81796  Web Order